[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npx prisma generate && npm run build --prefix server"

[deploy]
startCommand = "node server/dist/index.js"
restartPolicyType = "ON_FAILURE"
